### PR TITLE
Use ansible_python_interpreter=auto

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request makes the change of using `ansible_python_interpreter=auto` wherever possible.

## 💭 Motivation and Context

In the future, `ansible_python_interpreter=auto` will be Ansible's default behavior, so it makes sense to go ahead and prepare for it.  Since we remove python2, it should not change the AMI that is generated.

## 🧪 Testing

I have successfully generated a staging AMI with these changes.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dav3r** [comment]
How come I don't see any commits like [this one](https://github.com/cisagov/freeipa-server-packer/pull/21/commits/47100320165bd7ab7644808ce0a87f449548255e) in this PR?

**Comment by jsf9k** [comment]
> How come I don't see any commits like [this one](https://github.com/cisagov/freeipa-server-packer/pull/21/commits/47100320165bd7ab7644808ce0a87f449548255e) in this PR?

I created a branch and tried that here, but it doesn't work.  Ansible's [internal table mapping OS distro versions to python versions](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml#L1450-L1500) does not include Kali, and the list of python versions to search if there is no entry in the table does not include  python3.8.  Python3.8 is the latest release on Kali (which is based on Debian Testing, currently Debian Bullseye).

It may be possible to move to using `ansible_python_interpreter=auto` with Kali in a future version of Ansible, but for now I have to force the use of `/usr/bin/python3`.  I was torn between forcing `/usr/bin/python3` everywhere versus setting Ansible to use the future default behavior everywhere I can and making Kali a special case.

**Comment by dav3r** [comment]
> I created a branch and tried that here, but it doesn't work. Ansible's [internal table mapping OS distro versions to python versions](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml#L1450-L1500) does not include Kali, and the list of python versions to search if there is no entry in the table does not include python3.8. Python3.8 is the latest release on Kali (which is based on Debian Testing, currently Debian Bullseye).
> 
> It may be possible to move to using `ansible_python_interpreter=auto` with Kali in a future version of Ansible, but for now I have to force the use of `/usr/bin/python3`. I was torn between forcing `/usr/bin/python3` everywhere versus setting Ansible to use the future default behavior everywhere I can and making Kali a special case.

Understood, but now this PR name and description is a bit confusing.  Can you please do something about that?

**Comment by jsf9k** [comment]
> Understood, but now this PR name and description are a bit confusing. Can you please do something about that?

Ah, I was confused.  I saw "teamserver" and thought "Kali".  This teamserver is based on Debian Buster, not Kali.  I will fix it.  I have bewildered myself!

**Comment by dav3r** [comment]
> > Understood, but now this PR name and description are a bit confusing. Can you please do something about that?
> 
> Ah, I was confused. I saw "teamserver" and thought "Kali". This teamserver is based on Debian Buster, not Kali. I will fix it. I have bewildered myself!
> 
> I did, however, explain why I can't do the same thing in [cisagov/kali-packer](https://github.com/cisagov/kali-packer).

Ah, thanks for clearing that up.  Your comment had me thinking that the Teamserver was based on Kali, but now everything makes sense again. 👍

**Comment by jsf9k** [comment]
> A chao, perspicua. ("From chaos, clarity.")

I hadn't heard that one.  Freemasons have a similar saying: Ordo ab chao.  (From chaos comes order.)

**Comment by dav3r** [comment]
> > A chao, perspicua. ("From chaos, clarity.")
> 
> I hadn't heard that one. Freemasons have a similar saying: Ordo ab chao. (From chaos comes order.)

That's because I just made it up with the help of Google Translate. 😄 Seemed appropriate enough.  I knew there was similar phrase, but wasn't exactly sure what it was.

**Comment by jsf9k** [comment]
After spending a lot of time wondering why this doesn't work, I have discovered that [`INTERPRETER_PYTHON_DISTRO_MAP` in Ansible 2.9.7](https://github.com/ansible/ansible/blob/v2.9.7/lib/ansible/config/base.yml#L1435-L1450) _does not_ include the `debian` entry [seen in the `devel` branch](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml#L1469-L1486).  These changes will not work as expected until those changes find their way into an Ansible release.

Investigating further, I found that the `INTERPRETER_PYTHON_DISTRO_MAP` changes [will not be released until Ansible 2.10](https://github.com/ansible/ansible/pull/63097#pullrequestreview-303970533).

**Pull request closed without merging**
